from urllib.parse import quote

from fastapi import APIRouter, Depends, Form, UploadFile
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, verify_csrf
from app.core.exceptions import QuizNotFoundError
from app.models.user_data import User
from app.schemas.quiz import DeleteQuizResponse, QuizListResponse, QuizResponse, QuizType
from app.services.document_export_service import export_quiz, export_quizzes_zip
from app.services.quiz_service import (
    delete_quiz,
    generate_quiz,
    get_quiz_with_questions,
    list_quizzes,
)

router = APIRouter()


def _content_disposition(filename: str) -> str:
    """Builds a Content-Disposition header safe for any Unicode filename.
    HTTP headers must be Latin-1 — a quiz title generated by the AI can
    contain characters outside that range (curly quotes, em dashes, etc.),
    which previously crashed this response with a raw UnicodeEncodeError.
    Provides both a plain ASCII fallback (filename=) for older clients and
    the RFC 5987/6266 UTF-8 form (filename*=) for everything else."""
    ascii_fallback = filename.encode("ascii", errors="replace").decode("ascii").replace('"', "")
    utf8_encoded = quote(filename)
    return f'attachment; filename="{ascii_fallback}"; filename*=UTF-8\'\'{utf8_encoded}'


@router.get("", response_model=QuizListResponse)
async def get_quizzes(
    user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)
):
    quizzes = await list_quizzes(db, str(user.id))
    return QuizListResponse(
        quizzes=[
            QuizResponse(
                id=str(q.id),
                title=q.title,
                questionCount=q.question_count,
                quizType=q.quiz_type,
                createdAt=q.created_at,
            )
            for q in quizzes
        ]
    )


@router.post("", response_model=QuizResponse, dependencies=[Depends(verify_csrf)])
async def create_quiz(
    file: UploadFile,
    quizType: QuizType = Form(...),
    questionCount: int = Form(...),
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    quiz = await generate_quiz(
        db,
        user_id=str(user.id),
        user_email=user.email,
        file=file,
        quiz_type=quizType,
        question_count=questionCount,
    )
    return QuizResponse(
        id=str(quiz.id),
        title=quiz.title,
        questionCount=quiz.question_count,
        quizType=quiz.quiz_type,
        createdAt=quiz.created_at,
        direction=quiz.direction,
    )


@router.get("/download")
async def download_quizzes(
    ids: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    quiz_ids = ids.split(",")

    if len(quiz_ids) == 1:
        quiz, questions = await get_quiz_with_questions(db, str(user.id), quiz_ids[0])
        docx_bytes = export_quiz(quiz, questions)
        return StreamingResponse(
            iter([docx_bytes]),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": _content_disposition(f"{quiz.title}.docx")},
        )

    # Fetch each requested quiz individually rather than failing the whole
    # batch on the first missing/not-owned id. A quiz can easily disappear
    # between the user selecting it and clicking download (deleted in
    # another tab, id typo, etc.) — that shouldn't cost them the other
    # quizzes in the same batch. Missing ids are reported the same way
    # export_quizzes_zip already reports per-quiz export failures, so the
    # frontend's existing X-Failed-Titles handling covers both cases
    # uniformly.
    quizzes_with_questions = []
    failed_titles: list[str] = []
    for qid in quiz_ids:
        try:
            quizzes_with_questions.append(await get_quiz_with_questions(db, str(user.id), qid))
        except QuizNotFoundError:
            # No title available since the quiz was never fetched — a raw
            # id isn't meaningful to show in the UI, so use a readable
            # placeholder instead of leaking a UUID into failedTitles.
            failed_titles.append("Quiz no longer available")

    zip_bytes, export_failed_titles = export_quizzes_zip(quizzes_with_questions)
    failed_titles.extend(export_failed_titles)

    headers = {"Content-Disposition": 'attachment; filename="quizzes.zip"'}
    if failed_titles:
        # Same Latin-1 restriction as Content-Disposition applies to any
        # custom header — encode each title so a non-ASCII quiz title
        # (curly quotes, etc.) can't crash this response. Exposing this
        # header to the frontend is configured centrally in main.py's
        # CORSMiddleware, not per-response.
        headers["X-Failed-Titles"] = ",".join(quote(title) for title in failed_titles)

    return StreamingResponse(
        iter([zip_bytes]),
        media_type="application/zip",
        headers=headers,
    )

@router.get("/{quiz_id}", response_model=QuizResponse)
async def get_quiz_by_id(
    quiz_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    quiz, questions = await get_quiz_with_questions(db, str(user.id), quiz_id)
    return QuizResponse(
        id=str(quiz.id),
        title=quiz.title,
        questionCount=quiz.question_count,
        quizType=quiz.quiz_type,
        createdAt=quiz.created_at,
        direction=quiz.direction,
        questions=[
            {
                "number": q.question_order,
                "text": q.question_text,
                "type": quiz.quiz_type,
                "options": q.options,
                "answer": q.correct_answer,
            }
            for q in questions
        ],
    )


@router.delete("/{quiz_id}", response_model=DeleteQuizResponse, dependencies=[Depends(verify_csrf)])
async def delete_quiz_by_id(
    quiz_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await delete_quiz(db, str(user.id), user.email, quiz_id)
    return DeleteQuizResponse(message="Quiz deleted.")