import type { LegalContentItem } from "./terms";

export const disclaimer: LegalContentItem = {
  title: "Disclaimer",
  sections: [
    {
      q: "AI-generated content",
      a: "Quizzes and explanations generated by MindBlow are produced by AI and may contain inaccuracies. Always verify important information independently. MindBlow is a study aid, not a substitute for professional instruction.",
    },
    {
      q: "Educational use only",
      a: "MindBlow is designed for educational and personal learning purposes. It should not be used as the sole basis for academic assessments, certifications, or professional evaluations.",
    },
    {
      q: "No guarantee of results",
      a: "While MindBlow is designed to help you study more effectively, we cannot guarantee specific academic outcomes, test scores, or learning results. Individual results will vary.",
    },
    {
      q: "External links and content",
      a: "MindBlow may process content from URLs you provide. We are not responsible for the accuracy, legality, or appropriateness of third-party content processed through our service.",
    },
  ],
};