"""add revoked_at to refresh_tokens

Revision ID: 25a4c85d99b7
Revises: 618a30ffafc7
Create Date: 2026-07-31 14:34:05.492914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a4c85d99b7'
down_revision: Union[str, Sequence[str], None] = '618a30ffafc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
