"""create prompt_context and announcement_log tables

Revision ID: 444e6a3d92b8
Revises: d98ba177680e
Create Date: 2026-07-22 18:41:29.577259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444e6a3d92b8'
down_revision: Union[str, Sequence[str], None] = 'd98ba177680e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('objectives', sa.String(), nullable=False),
    sa.Column('constraints', sa.String(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_context')
    op.drop_table('announcement_log')
    # ### end Alembic commands ###
