"""remove opted_in_marketing and announcement tables

Revision ID: 7d22b55fc467
Revises: 6e92a645e0b9
Create Date: 2026-07-29 19:49:22.700516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d22b55fc467'
down_revision: Union[str, Sequence[str], None] = '6e92a645e0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_log')
    op.drop_column('users', 'opted_in_marketing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opted_in_marketing', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('announcement_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('announcement_log_pkey'))
    )
    # ### end Alembic commands ###
