"""add quiz direction column and quiz_question table

Revision ID: ceeb64152b18
Revises: 444e6a3d92b8
Create Date: 2026-07-27 18:22:21.127591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceeb64152b18'
down_revision: Union[str, Sequence[str], None] = '444e6a3d92b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('direction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'direction')
    # ### end Alembic commands ###
